### ISSUE TITLE
arm compiled version?

### ISSUE THREAD

**Issue by hilldani** [intel/svr-info#30]
when attempting to run the svr-info release binary on ARM it says
```sh
$ ./svr-info 
-bash: ./svr-info: cannot execute binary file

$ objdump -a svr-info
svr-info:     file format elf64-x86-64
```
Will svr-info support an official ARM binary build?

**Comment by harp-intel** [comment]
We have no plans to build/release a svr-info binary that runs on ARM. Currently, one can run svr-info on an x86 system and target a remote ARM server. The basic information from that remote server will be retrieved.

**Comment by hilldani** [comment]
can the collector be run manually then generate a report from it later without targeting via ssh?

**Comment by harp-intel** [comment]
The current release embeds the collector and reporter, among other things, into the svr-info binary, so the ARM collector binary isn't accessible unless built from source. Assuming it is built from source, then yes, it can be run manually. 

The collector input YAML file will need to be created from the template (https://github.com/intel/svr-info/blob/main/src/orchestrator/resources/collector_reports.yaml.tmpl) manually as well, since svr-info typically takes care of this. I believe you would only need to set the three values under "arguments".

The reporter can be run directly from svr-info (on x86) by passing the -reporter flag and reporter options on the command line.

**Comment by hilldani** [comment]
thank you!
